name: wisata_kebonayu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/images/header/

  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
    - family: Roboto_Condensed
      fonts:
        - asset: fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
    - family: 
      fonts:
        - asset: fonts/Raleway/Raleway-VariableFont_wght.ttf

